CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_NFCT_PINS_AS_GPIOS=y //not needed tbh

# Explicitly enables Bluetooth and Split features
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y

# Uncomment for RGB support. See the relevant options in the documentation
# https://zmk.dev/docs/features/underglow#configuring-rgb-underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
